# Generated by Django 3.2.24 on 2025-09-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('company_log', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('ai_ml', 'AI/ML Startup'), ('education', 'Education')], default='tech', max_length=200)),
                ('ml_projects', models.TextField(blank=True, help_text='ML/AI projects worked on')),
                ('algorithms_used', models.CharField(blank=True, help_text='Algorithms and techniques used', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=1)),
                ('category', models.CharField(choices=[('backend', 'Backend Development'), ('frontend', 'Frontend Development'), ('database', 'Database'), ('devops', 'DevOps & Tools'), ('ml', 'Machine Learning'), ('ai', 'Artificial Intelligence'), ('data_science', 'Data Science'), ('blockchain', 'Blockchain & Crypto'), ('cloud', 'Cloud & AI Services'), ('soft', 'Soft Skills')], default='backend', max_length=20)),
                ('subcategory', models.CharField(blank=True, choices=[('supervised', 'Supervised Learning'), ('unsupervised', 'Unsupervised Learning'), ('reinforcement', 'Reinforcement Learning'), ('deep_learning', 'Deep Learning'), ('nlp', 'Natural Language Processing'), ('computer_vision', 'Computer Vision'), ('time_series', 'Time Series Analysis')], help_text='Specialized subcategory', max_length=20, null=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('framework', models.CharField(blank=True, help_text='pytorch,Django, etc', max_length=50)),
                ('library', models.CharField(blank=True, help_text='comma separeted library names', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', '-level', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('project_type', models.CharField(choices=[('web', 'Web Application'), ('mobile', 'Mobile Application'), ('ml', 'Machine Learning'), ('ai', 'Artificial Intelligence'), ('blockchain', 'Blockchain/Crypto'), ('data', 'Data Science'), ('iot', 'IoT'), ('desktop', 'Desktop Application')], default='web', max_length=20)),
                ('url', models.URLField(blank=True, null=True, verbose_name='Project URL')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Github URL')),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Display order (higher numbers shows first)')),
                ('model_accuracy', models.FloatField(blank=True, null=True, verbose_name='Model Accuracy (%)')),
                ('algorithm', models.CharField(blank=True, help_text='ML Algorithm used', max_length=100)),
                ('dataset_size', models.CharField(blank=True, help_text='Dataset size (e.g., 10GB, 1M records)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(blank=True, help_text='Display separated by commas', to='main.Skills')),
            ],
            options={
                'ordering': ['-featured', '-order', '-created_at'],
            },
        ),
    ]
